### ISSUE TITLE
Apollo Starter is out of date

### ISSUE THREAD

**Issue by DxCx** [apollographql/apollo-tutorial-kit#27]
As subject says.
very old code. :(

**Comment by tab00** [comment]
Will it be updated? I was thinking of trying Apollo but this is stopping me.

**Comment by DxCx** [comment]
@helfer :)

**Comment by helfer** [comment]
@tab00 Thanks for the reminder. If I update the code, I will have to make a new video. I'll try to make some time for that this week or next week! Maybe I can even squeeze in a full-stack example 🙂

**Comment by tab00** [comment]
Thanks, though just to let you know, we don't really need video.

**Comment by helfer** [comment]
@tab00 what I'm doing now is making a new series of tutorials instead.
