### ISSUE TITLE
Received ReferenceError when starting up due to missing babel plugin

### ISSUE THREAD

**Issue by JasonSooter** [apollographql/apollo-tutorial-kit#30]
When starting up the app for the first time

ReferenceError: Unknown plugin "babel-plugin-inline-import" specified in "/Users/jasonsooter/dev-space/shipcertainio/backend/.babelrc"

I added `"babel-plugin-inline-import": "2.0.5",` to the package.json. Ran Yarn again to install the plugin. It then started up fine. Should this plugin be added to package.json or is it something I did?

I can submit a pull request if that is the correct solution. If not, I'll happily be corrected.

Thanks!

**Comment by helfer** [comment]
Hey Jason, thanks for filing an issue. Can you tell me if this was on the master branch or on the server-only branch?

**Comment by JasonSooter** [comment]
@helfer It was after running:

git clone https://github.com/apollographql/apollo-tutorial-kit

I was in the 'Setting Up' step of following along with this tutorial:

https://dev-blog.apollodata.com/tutorial-building-a-graphql-server-cddaa023c035

I didn't intentionally change the branch from master. I do see that package got removed a couple days ago in your 'Merge server-only into master' commit. 

I hope that's helpful

**Comment by helfer** [comment]
Ok, thanks, let me check if I can reproduce the error!

**Comment by helfer** [comment]
Thanks @JasonSooter! I fixed it by removing the plugin in .babelrc, because it turns out it wasn't needed (we used it for parsing .graphql files, but we don't have any atm).

**Comment by JasonSooter** [comment]
@helfer Great! Thanks for the good starter kit. Have a Great Day!
