### ISSUE TITLE
Unsued file: `data/schema.graphql`

### ISSUE THREAD

**Issue by dterei** [apollographql/apollo-tutorial-kit#31]
Not sure if deliberate but changes in #18 were dropped from the code, but one of the files it added `data/schema.graphql` left in place still. This is confusing as a new user (i.e., me) is trying to understand all the pieces and gets thrown by a unused file duplicating the schema.

Easiest solution is to just kill `data/schema.graphql`, but not clear if wanted so issue rather than PR.

**Comment by helfer** [comment]
Thanks @dterei, I've deleted the file!
