### ISSUE TITLE
Remove GraphQL peerDependency

### ISSUE THREAD

**Issue by schmidsi** [apollographql/apollo-tutorial-kit#33]
Why is GraphQL listed as peerDependency? Afaik, peer deps are only necessary on modules, not on standalone apps. It throws errors after `npm install`:

    npm WARN melon-graphql-server@0.1.0 requires a peer of graphql@^0.5.0 || ^0.6.0 but none was installed.

https://github.com/apollographql/apollo-tutorial-kit/blob/master/package.json#L50

    "peerDependencies": {
      "graphql": "^0.5.0 || ^0.6.0"
    },

Suggestion: Add graphql as normal dependency.

**Comment by johannakate** [comment]
Thanks!
