### ISSUE TITLE
Resolvers returning null (Step 4)

### ISSUE THREAD

**Issue by jdhines** [apollographql/apollo-tutorial-kit#44]
I have been following along, and everything was working with the mocks, but I can't for the life of me get the resolvers to return anything but null. I've gone through Step 4 a dozen times, read Apollo and Graphql.org docs, checked SO, but haven't been able to figure out why the resolvers aren't working.
[See my fork.](https://github.com/jdhines/apollo-tutorial-kit-jdhines/tree/master/data)

**Comment by cschwendtner** [comment]
@jdhines: Could you please try changing
import { resolvers } from "./resolvers";
in schema.js to
import resolvers from "./resolvers";

**Comment by jdhines** [comment]
![genie](https://user-images.githubusercontent.com/2855641/39252216-29e26110-4873-11e8-9fe0-d8b328b40d63.gif)

One of the things I'm still not 100% on in JavaScript (among many) is imports, but this makes sense since I didn't have a named import. I would have thought VS Code would have caught this though. Thanks.
